CREATE TYPE staff_role AS ENUM('SUPER_ADMIN','BRANCH1','BRANCH2');
CREATE TYPE import_row_status AS ENUM('CREATED','OK','ERROR');
CREATE TABLE branches(id serial PRIMARY KEY,name text NOT NULL,latitude numeric,longitude numeric,pincode text);
CREATE TABLE users(id serial PRIMARY KEY,username text UNIQUE NOT NULL,hashed_pw text NOT NULL,role_enum staff_role NOT NULL,branch_id int REFERENCES branches(id));
CREATE TABLE product_categories(id serial PRIMARY KEY,parent_id int REFERENCES product_categories(id),name text NOT NULL,slug text NOT NULL,gender text NOT NULL,level int NOT NULL,sort_order int DEFAULT 0,is_active boolean DEFAULT true,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE products(id serial PRIMARY KEY,name text NOT NULL,brand_name text NOT NULL,pattern_code text,fit_type text,gender text,category_id int REFERENCES product_categories(id));
CREATE TABLE product_variants(id serial PRIMARY KEY,product_id int REFERENCES products(id),size text NOT NULL,colour text NOT NULL,fit text,mrp numeric NOT NULL,sale_price numeric,cost_price numeric,b2c_discount_pct numeric DEFAULT 0,b2b_discount_pct numeric DEFAULT 0,image_url text,is_active boolean DEFAULT true,created_at timestamptz DEFAULT now(),UNIQUE(product_id,size,colour,fit));
CREATE TABLE barcodes(id serial PRIMARY KEY,variant_id int REFERENCES product_variants(id),ean_code text UNIQUE);
CREATE TABLE branch_variant_stock(branch_id int REFERENCES branches(id),variant_id int REFERENCES product_variants(id),on_hand int DEFAULT 0,reserved int DEFAULT 0,is_active boolean DEFAULT true,PRIMARY KEY(branch_id,variant_id));
CREATE TABLE product_images(id serial PRIMARY KEY,ean_code text UNIQUE,image_url text,uploaded_at timestamptz DEFAULT now());
CREATE TABLE product_colour_images(id serial PRIMARY KEY,product_id int REFERENCES products(id),colour text,fit text,image_url text,cloudinary_public_id text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE UNIQUE INDEX product_colour_unique ON product_colour_images(product_id,lower(btrim(colour)),lower(btrim(COALESCE(fit,''))));
CREATE TABLE import_jobs(id bigserial PRIMARY KEY,file_name text,file_url text,uploaded_by int,status_enum text,rows_total int,rows_success int,rows_error int,branch_id int,uploaded_at timestamptz DEFAULT now(),completed_at timestamptz);
CREATE TABLE import_rows(id bigserial PRIMARY KEY,import_job_id bigint REFERENCES import_jobs(id),raw_row_json jsonb,status_enum import_row_status,error_msg text);
CREATE TABLE userstaras(id serial PRIMARY KEY,name text,email text UNIQUE,mobile text,type text,password text,city text);
CREATE TABLE sales(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source text,customer_email text,customer_name text,customer_mobile text,login_email text,shipping_address jsonb,status text,payment_status text,payment_method text,payment_ref text,totals jsonb,branch_id int,total numeric,created_at timestamptz DEFAULT now(),is_b2b boolean DEFAULT false,notes text);
CREATE TABLE sale_items(id bigserial PRIMARY KEY,sale_id uuid REFERENCES sales(id),product_id int,variant_id int REFERENCES product_variants(id),qty int,price numeric,mrp numeric,size text,colour text,image_url text,ean_code text,pack_size int DEFAULT 1,created_at timestamptz DEFAULT now());
CREATE TABLE tarascart(id serial PRIMARY KEY,user_id int,product_id int,quantity int,selected_size text,selected_color text,updated_at timestamptz DEFAULT now());
CREATE TABLE coin_settings(key text PRIMARY KEY,value text);
CREATE TABLE coin_wallets(user_id int PRIMARY KEY,balance numeric DEFAULT 0,signup_coins_remaining numeric DEFAULT 0,paid_orders_count int DEFAULT 0,updated_at timestamptz DEFAULT now());
CREATE TABLE coin_transactions(id serial PRIMARY KEY,user_id int,amount numeric,type text,sale_id uuid,note text,created_at timestamptz DEFAULT now());
CREATE TABLE shipments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),sale_id uuid,branch_id int,shiprocket_order_id text,shiprocket_shipment_id text,awb text,label_url text,tracking_url text,status text,created_at timestamptz DEFAULT now());
CREATE TABLE order_cancellations(id serial PRIMARY KEY,sale_id uuid UNIQUE,payment_type text,reason text,cancellation_source text,created_at timestamptz DEFAULT now());
CREATE TABLE payments(id serial PRIMARY KEY,sale_id uuid,razorpay_order_id text UNIQUE,razorpay_payment_id text,status text,amount_paise bigint,currency text,email text,phone text,notes jsonb,method text,created_at timestamptz DEFAULT now());
CREATE TABLE b2b_products(id bigserial PRIMARY KEY,style_code text,brand_name text,product_name text,gender text,mrp numeric,markdown_pct numeric,stock_unit text,stock_qty int,pieces_per_box int,avb_sizes text,colour text,design_pattern text,fit text,is_active boolean DEFAULT true,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE b2b_stock_movements(id bigserial PRIMARY KEY,product_id bigint,delta int,reason text,admin_user text,created_at timestamptz DEFAULT now());
